name: Build Typst PDF

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Fira Sans and Fira Math fonts
        run: |
          set +x
          #
          sudo apt-get update
          sudo apt-get install -y wget unzip fontconfig
          #
          # Install Fira Sans from Google Fonts
          # https://github.com/google/fonts
          #
          wget -qO fira-sans.zip https://github.com/google/fonts/archive/refs/heads/main.zip
          unzip -q fira-sans.zip '*/ofl/firasans/*' -d firasans-temp
          sudo mkdir -p /usr/share/fonts/truetype/fira-sans
          sudo cp firasans-temp/*/ofl/firasans/*.ttf /usr/share/fonts/truetype/fira-sans/
          rm -rf firasans-temp fira-sans.zip
          #
          # Install Fira Math from GitHub
          # https://github.com/firamath/firamath/releases
          #
          wget -qO FiraMath-Regular.otf https://github.com/firamath/firamath/releases/download/v0.3.4/FiraMath-Regular.otf
          sudo mkdir -p /usr/share/fonts/truetype/fira-math
          sudo cp FiraMath-Regular.otf /usr/share/fonts/truetype/fira-math/
          rm -rf FiraMath-Regular.otf
          #
          # Refresh font cache
          #
          sudo fc-cache -fv

      - name: Setup Typst
        uses: typst-community/setup-typst@v4

      - name: Font check
        run: typst fonts

      - name: Compile Typst to PDF
        run: typst compile main.typ rust-1st-impressions.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust-1st-impressions-pdf
          path: rust-1st-impressions.pdf
