name: Build Typst PDF

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Fira Sans and Fira Math fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-fira fonts-firamath

      - name: Setup Typst
        uses: typst-community/setup-typst@v4

      - name: Compile Typst to PDF
        run: typst compile main.typ main.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: typst-pdf
          path: main.pdf
