name: Build Typst PDF

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Fira Sans and Fira Math fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip fontconfig
          # Install Fira Sans from Google Fonts
          wget -qO fira-sans.zip https://github.com/google/fonts/archive/refs/heads/main.zip
          unzip -q fira-sans.zip '*/ofl/firasans/*' -d firasans-temp
          sudo mkdir -p /usr/share/fonts/truetype/fira-sans
          sudo cp firasans-temp/*/ofl/firasans/*.otf /usr/share/fonts/truetype/fira-sans/
          rm -rf firasans-temp fira-sans.zip
          # Install Fira Math from GitHub
          wget -q https://github.com/firamath/firamath/releases/latest/download/firamath-otf.zip
          unzip -q firamath-otf.zip -d firamath-temp
          sudo mkdir -p /usr/share/fonts/truetype/fira-math
          sudo cp firamath-temp/*.otf /usr/share/fonts/truetype/fira-math/
          rm -rf firamath-temp firamath-otf.zip
          # Refresh font cache
          sudo fc-cache -fv

      - name: Setup Typst
        uses: typst-community/setup-typst@v4

      - name: Compile Typst to PDF
        run: typst compile main.typ main.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: typst-pdf
          path: main.pdf
